CREATE TABLE live_alert_alerts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 user_id INTEGER REFERENCES live_alert_users(id) ON DELETE CASCADE NOT NULL,
 alert_time TIMESTAMP DEFAULT now(),
 longitude FLOAT,
 latitude FLOAT,
 alert_active BOOLEAN DEFAULT false
);